export const developers: string[] = [
  'Adam Green',
  'Brian Miller',
  'Catherine Lee',
  'David Foster',
  'Emily Harris',
  'Frank Watson',
  'George Morris',
  'Hannah Kim',
  'Isaac Martin',
  'Julia Scott',
  'Kevin Chen',
  'Liam Gallagher',
  'Mia Thompson',
  'Nate Wilson',
  'Olivia Palmer',
  'Peter Johnson',
  'Quinn Sullivan',
  'Ryan Mitchell',
  'Tara Kim',
  'Vanessa Martinez'
];