// defines a list of product names for the static data
export const productNames: string[] = [
  'Connect',
  'Transit Tracker',
  'Parks Explorer',
  'Health Navigator',
  'Education Portal',
  'Environmental Assessment Tool',
  'Business Registry',
  'Disaster Response System',
  'Fire Information System',
  'Emergency Management Platform',
  'Climate Change Tracker',
  'Housing Locator',
  'Justice System Tracker',
  'Childcare Finder',
  'Indigenous Language Learning App',
  'Invasive Species Reporting Tool',
  'Job Matchmaker',
  'Electoral Boundary Mapping Tool',
  'Public Safety Alert System',
  'Tourism Guide',
  'Energy Efficiency Calculator',
  'Water Quality Monitoring System',
  'Agriculture Network',
  'Waste Management Tracker',
  'Volunteer Hub',
  'Youth Employment Resource',
  'Social Housing Registry',
  'Pension Calculator',
  'Coastal Navigation Tool',
  'Food Safety Network',
  'Wildlife Observation App',
  'Air Quality Index',
  'Greenhouse Gas Emissions Tracker',
  'Emergency Contact List',
  'Vehicle Registration Portal',
  'Land Use Planner',
  'Marine Conservation Tool',
  'Parenting Resource Hub',
  'Rental Housing Registry',
  'Renewable Energy Planner',
]